defmodule HashColorAvatar do
  @default_shape :circle
  @default_size 100
  @default_saturation 50
  @default_value 90
  @font_family "ui-sans-serif, system-ui, -apple-system, Segoe UI, Roboto, Helvetica, Arial, 'Apple Color Emoji', 'Segoe UI Emoji'"
  @initial_fallback "VK"
  @max_hue 360

  @moduledoc """
  This is a small library to generate SVG initial avatar with unique-ish color based on string hash.

  The primary feature is to generate on the fly SVG for default avatar. The user can get unique avatar (to certain degree) based on his name innitial and the unique color generated by hashing its name. Please be noted that of couse same name will resulting to the same image. And eventhough there are thousands of color exist, we choose to make the saturation fix so there can only be 359 possible color.

  Another function will be quite useful as well such as random_color/1, will give you nice pastel random color which you can use as background or anything.

  set_color/2 can be used to make color by specifying the hue value.

  Function to Generate Initial from name, gen_initial/1 can also be used independently.

  """

  @doc """
  Will generate random color in hex.

  ## Options
  This color is generated by randomizing HSV (Hue Saturation Value) with default Saturation is set to 50 and Value set to 90.
  ``` iex> HashColorAvatar.random_color([saturation: 70, value: 100])

  """

  def random_color(options \\ []) do
    <<n::unsigned-big-16>> = :crypto.strong_rand_bytes(2)

    # Hue range is 0..359, but we keep 1..359 to avoid the edge case where hue=0 can repeat more.
    seed = rem(n, @max_hue - 1) + 1
    saturation = Keyword.get(options, :saturation, @default_saturation)
    value = Keyword.get(options, :value, @default_value)
    hsv_to_rgb(%{hue: seed, saturation: saturation, value: value}) |> rgb_to_hex()
  end

  defp normalize_hue(hue_value) when is_integer(hue_value) do
    rem(hue_value, @max_hue)
  end

  defp normalize_hue(hue_value) when is_float(hue_value) do
    hue_value |> trunc() |> normalize_hue()
  end

  defp normalize_hue(hue_value) do
    hue_value |> to_string() |> String.to_integer() |> normalize_hue()
  end

  defp clamp_int(value, min, max) when is_integer(value) do
    cond do
      value < min -> min
      value > max -> max
      true -> value
    end
  end

  defp as_float(v), do: v * 1.0

  defp clamp_float(value, min, max) do
    value = as_float(value)

    cond do
      value < min -> min
      value > max -> max
      true -> value
    end
  end

  @doc """
  This function will convert RGB to hex.

  ## Examples

      iex> HashColorAvatar.set_color(12)
      "#E58972"

  Option also applied

      iex> HashColorAvatar.set_color(12, [saturation: 70, value: 80])
      "#CC593D"

  """
  def set_color(hue_value, options \\ []) do
    saturation = Keyword.get(options, :saturation, @default_saturation)
    value = Keyword.get(options, :value, @default_value)

    hsv_to_rgb(%{hue: normalize_hue(hue_value), saturation: saturation, value: value})
    |> rgb_to_hex()
  end

  @doc """
  This function will convert HSV map to RGB map.

  ## Examples

      iex> HashColorAvatar.hsv_to_rgb(%{hue: 17, saturation: 50, value: 90})
      %{blue: 114, green: 147, red: 229}

  """
  def hsv_to_rgb(%{hue: hue, saturation: saturation, value: value} = _hsv) do
    hue = normalize_hue(hue)
    saturation = clamp_float(saturation, 0, 100)
    value = clamp_float(value, 0, 100)

    h = hue / 60
    i = Float.floor(h) |> trunc()
    f = h - i

    sat_dec = saturation / 100

    p = value * (1 - sat_dec)
    q = value * (1 - sat_dec * f)
    t = value * (1 - sat_dec * (1 - f))

    p_rgb = get_rgb_color(p)
    v_rgb = get_rgb_color(value)
    t_rgb = get_rgb_color(t)
    q_rgb = get_rgb_color(q)

    case i do
      0 -> %{red: v_rgb, green: t_rgb, blue: p_rgb}
      1 -> %{red: q_rgb, green: v_rgb, blue: p_rgb}
      2 -> %{red: p_rgb, green: v_rgb, blue: t_rgb}
      3 -> %{red: p_rgb, green: q_rgb, blue: v_rgb}
      4 -> %{red: t_rgb, green: p_rgb, blue: v_rgb}
      _ -> %{red: v_rgb, green: p_rgb, blue: q_rgb}
    end
  end

  @doc """
  This function will convert RGB to hex.

  ## Examples

      iex> HashColorAvatar.rgb_to_hex(%{red: 12, green: 23, blue: 43})
      "#0C172B"

      iex> HashColorAvatar.rgb_to_hex(%{red: 121, green: 13, blue: 203})
      "#790DCB"

  """
  def rgb_to_hex(%{red: red, green: green, blue: blue} = _rgb) do
    r = clamp_int(red, 0, 255)
    g = clamp_int(green, 0, 255)
    b = clamp_int(blue, 0, 255)

    "#" <> Base.encode16(<<r, g, b>>, case: :upper)
  end

  @doc """
  Given some string, this function will generate SVG avatar. The main feature is the micro hasing function. Which means th ecolor given for "Frank Abraham" will be different for "Foreman Abdul" even though they both have same initials.

  ## Examples

      iex> HashColorAvatar.gen_avatar("", style: :modern) |> to_string() |> String.contains?("<linearGradient")
      true

  ## Option
  **:color** can be used to specify background color. By default it will generate hash based on the text given. It will be unique-ish since there are only 359 possible color and there's a chance it looks similar one amongst the other. For the value you can choose "random", any color code recognized by CSS such as "teal", "tomato", also it accept hex code.

  **:shape** by default is circle. You can also choose "rect" for rectangle avatar.

  **:style** controls the SVG look:
  - `:minimal` (default): solid background, no gradient/shadow filters (good for icons)
  - `:modern`: gradient background + subtle drop shadow + highlight overlay + ring

  **:size** You can define how many pixel height and width. Default is 100

  **:text_color** changes the initials color (default: "white").

  **:font_family** changes the font family used for the initials.

  ## Examples

      iex> HashColorAvatar.gen_avatar("Samantha Johnson Abigail", [color: "tomato", shape: "rect", size: 200]) |> to_string() |> String.contains?("<rect")
      true


  """
  def gen_avatar(rawtext, options \\ []) do
    text = normalize_text(rawtext)

    color_opt = Keyword.get(options, :color, nil)
    shape_opt = normalize_shape(Keyword.get(options, :shape, @default_shape))
    size = validate_size!(Keyword.get(options, :size, @default_size))
    style_opt = normalize_style(Keyword.get(options, :style, :minimal))
    text_color = Keyword.get(options, :text_color, "white") |> to_string()
    font_family_opt = Keyword.get(options, :font_family, @font_family) |> to_string()

    initial = get_initial(text)
    fontsize = size / 2.4
    half = size / 2
    border_radius = max(ceil(size * 0.18), 10)

    svg_shape_and_fill =
      case style_opt do
        :modern ->
          id_suffix = :erlang.phash2({text, color_opt, shape_opt, size}) |> Integer.to_string(16)

          filter_svg =
            ~c{<filter id="shadow-#{id_suffix}" x="-20%" y="-20%" width="140%" height="140%"><feDropShadow dx="0" dy="#{size * 0.03}" stdDeviation="#{size * 0.05}" flood-color="black" flood-opacity="0.25" /></filter>}

          {defs_svg, bg_fill_attr} =
            case color_opt do
              nil ->
                hue = minihash(text)
                c1 = set_color(hue)
                c2 = set_color(rem(hue + 28, @max_hue), value: @default_value - 12)

                gradient_svg =
                  ~c{<linearGradient id="grad-#{id_suffix}" x1="0" y1="0" x2="1" y2="1"><stop offset="0%" stop-color="#{c1}" /><stop offset="100%" stop-color="#{c2}" /></linearGradient>}

                {
                  ~c{<defs>#{gradient_svg}#{filter_svg}</defs>},
                  ~c{fill="url(#grad-#{id_suffix})" filter="url(#shadow-#{id_suffix})"}
                }

              "grey" ->
                solid = "#c3c3c3"

                {~c{<defs>#{filter_svg}</defs>},
                 ~c{fill="#{solid}" filter="url(#shadow-#{id_suffix})"}}

              "black" ->
                solid = "#000000"

                {~c{<defs>#{filter_svg}</defs>},
                 ~c{fill="#{solid}" filter="url(#shadow-#{id_suffix})"}}

              "random" ->
                solid = random_color()

                {~c{<defs>#{filter_svg}</defs>},
                 ~c{fill="#{solid}" filter="url(#shadow-#{id_suffix})"}}

              custom ->
                solid = if is_binary(custom), do: custom, else: to_string(custom)

                {~c{<defs>#{filter_svg}</defs>},
                 ~c{fill="#{solid}" filter="url(#shadow-#{id_suffix})"}}
            end

          bg_shape =
            case shape_opt do
              "rect" ->
                ~c{<rect x="0" y="0" width="#{size}" height="#{size}" rx="#{border_radius}" ry="#{border_radius}" #{bg_fill_attr} />}

              _other ->
                ~c{<circle cx="#{half}" cy="#{half}" r="#{half}" #{bg_fill_attr} />}
            end

          overlay_svg =
            case shape_opt do
              "rect" ->
                ~c{<rect x="0" y="0" width="#{size}" height="#{size}" rx="#{border_radius}" ry="#{border_radius}" fill="#{text_color}" opacity="0.07" />}

              _other ->
                ~c{<circle cx="#{half}" cy="#{half}" r="#{half}" fill="#{text_color}" opacity="0.07" />}
            end

          ring_stroke_width = max(size * 0.03, 1)
          ring_border_radius = max(border_radius - 1, 0)

          ring_svg =
            case shape_opt do
              "rect" ->
                ~c{<rect x="1" y="1" width="#{max(size - 2, 0)}" height="#{max(size - 2, 0)}" rx="#{ring_border_radius}" ry="#{ring_border_radius}" fill="none" stroke="#{text_color}" stroke-opacity="0.25" stroke-width="#{ring_stroke_width}" />}

              _other ->
                ~c{<circle cx="#{half}" cy="#{half}" r="#{max(half - 1, 0)}" fill="none" stroke="#{text_color}" stroke-opacity="0.25" stroke-width="#{ring_stroke_width}" />}
            end

          {defs_svg, bg_shape, overlay_svg, ring_svg}

        :minimal ->
          solid =
            case color_opt do
              "grey" ->
                "#c3c3c3"

              "black" ->
                "#000000"

              "random" ->
                random_color()

              nil ->
                text |> minihash() |> set_color()

              custom ->
                if is_binary(custom), do: custom, else: to_string(custom)
            end

          bg_shape =
            case shape_opt do
              "rect" ->
                ~c{<rect x="0" y="0" width="#{size}" height="#{size}" rx="#{border_radius}" ry="#{border_radius}" fill="#{solid}" />}

              _other ->
                ~c{<circle cx="#{half}" cy="#{half}" r="#{half}" fill="#{solid}" />}
            end

          # Minimal output is meant to be easy to embed and customize externally.
          {~c{}, bg_shape, ~c{}, ~c{}}
      end

    {defs_svg, bg_shape, overlay_svg, ring_svg} = svg_shape_and_fill

    ~c{<svg width="#{size}" height="#{size}" viewBox="0 0 #{size} #{size}" xmlns="http://www.w3.org/2000/svg">#{defs_svg}#{bg_shape}#{overlay_svg}#{ring_svg}<text x="50%" y="50%" text-anchor="middle" dominant-baseline="middle" fill="#{text_color}" style="font-weight: 800; font-size: #{fontsize}px; font-family: #{font_family_opt};">#{initial}</text></svg>}
  end

  defp normalize_text(nil), do: "V K"
  defp normalize_text(text) when is_binary(text), do: text
  defp normalize_text(other), do: to_string(other)

  defp normalize_shape("rect"), do: "rect"
  defp normalize_shape(:rect), do: "rect"
  defp normalize_shape(_other), do: "circle"

  defp normalize_style(:modern), do: :modern
  defp normalize_style("modern"), do: :modern
  defp normalize_style(:minimal), do: :minimal
  defp normalize_style("minimal"), do: :minimal
  defp normalize_style(_other), do: :minimal

  defp validate_size!(size) when is_float(size), do: validate_size!(trunc(size))

  defp validate_size!(size) do
    cond do
      is_integer(size) and size > 0 ->
        size

      true ->
        raise ArgumentError,
              "expected :size to be a positive integer, got: #{inspect(size)}"
    end
  end

  @doc """
  This function generate initial from any given name. If more than 2 word given it will take initial first and last word. It will try to ignore other character.

  ## Examples

      iex> HashColorAvatar.get_initial("sujiwo tedjo")
      "ST"

      iex> HashColorAvatar.get_initial("guruh soekarno putra")
      "GP"

  """
  def get_initial(name) do
    clean_character =
      Regex.replace(~r/[\p{P}\p{S}\p{C}\p{N}]+/, name, "") |> String.trim() |> String.split()

    case Enum.count(clean_character) do
      0 ->
        @initial_fallback

      1 ->
        clean_character |> List.first() |> String.at(0) |> String.upcase()

      _other ->
        first = clean_character |> List.first() |> String.at(0) |> String.upcase()
        second = clean_character |> List.last() |> String.at(0) |> String.upcase()
        first <> second
    end
  end

  @doc false
  # Generate a stable integer hue in range 0..359 from any string.
  defp minihash(string) do
    hash = :crypto.hash(:md5, string)
    <<first4::binary-size(4), _rest::binary>> = hash
    value = :binary.decode_unsigned(first4)
    rem(value, @max_hue)
  end

  @doc false
  defp get_rgb_color(color) do
    (color * 255 / 100) |> trunc()
  end
end
